[Ml fonda] chapitre 5 - Régularisation & tradeoff biais-variance
ia-z/ia-z pull request #20
Opened 2022-03-19 21:42 UTC by Futurne

Premier jet du chapitre 5 pour le cours de ML foncamental. Dites moi ce que vous en pensez. Je me demande s'il ne faudrait pas appuyer la différence entre la régularisation L1 et L2, afin de savoir quand utiliser l'une ou l'autre (et j'ai essayé de trouver des réponses sur internet mais j'ai eu du mal à trouver quelque chose qui me convenait). De plus, j'ai mentionné rapidement le NFL, je me demande s'il est nécessaire de creuser plus ou pas de ce côté.

Bref, dites moi ce que vous en pensez !
Pierrot

2022-03-19 21:46 UTC, Futurne commented
Ah, et les équations mathématiques ne rendent pas bien sur github, pour des raisons de sécurité ils ne veulent pas compiler les équations maths pour les afficher sur leur site. Je pense cependant que lorsqu'on compile les markdown pour faire le site les équations apparaîtront (comme pour un jupyter notebook). Si vous voulez voir les équations, vous pouvez télécharger le markdown et le copier dans un notebook afin d'avoir tout de bien affiché.

Aussi, vous verrez que j'ai marqué une section de deux étoiles (**). C'est pour montrer que cette partie est un peu plus technique, mais qu'elle est sensée pouvoir être skippable par les lecteurs moins aisés avec les maths.

2022-03-22 10:27 UTC, tanguyesteoule reviewed
Première relecture, jusqu'à la ligne 118.
Globalement c'est très bien, j'ai corrigé quelques coquilles. Je trouve juste que le discours manque peut être un peu de fluidité. Ces notions sont assez théoriques et il faut bien veiller à pas perdre le lecteur. Pour cela il faut pas hésiter à partir d'une définition très basique avec un exemple et de la préciser ensuite.

2022-03-22 10:27 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +Lorsque l'on parle du *tradeoff biais-variance*, on parle du biais inductif et de la variance d'un modèle de machine learning.
Je trouve que le déroulé de cette partie n'est pas friendly. Je pense que l'intro doit être plus claire et plus simple à comprendre. Et il faut bien préciser que le biais et la variance sont deux **erreurs** provenant de sources différentes.

Pour moi il faudrait d'abord décrire rapidement le tradeoff biais-variance pour comprendre où l'on veut aller (On a deux sources d'erreurs incompatibles, on cherche un compromis entre les deux pour avoir le meilleur modèle possible) puis définir comme tu le fais le biais et la variance plus clairement (par exemple je trouve que c'est bizarre de commencer par "_Il est en fait impossible d'entraîner un modèle sans biais inductif_").

Peut être s'inspirer de la [page Wikipedia](https://fr.wikipedia.org/wiki/Dilemme_biais-variance) dont l'intro est bien je trouve : 
_Le biais est l'erreur provenant d’hypothèses erronées dans l'algorithme d'apprentissage. La variance est l'erreur due à la sensibilité aux petites fluctuations de l’échantillon d'apprentissage._

2022-03-22 10:27 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +choisi lorsque l'on entraîne le modèle !
```suggestion
choisit lorsque l'on entraîne le modèle !
```

2022-03-22 10:27 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +de générer toutes les données possibles d'une distribution fixée. On peut alors échantilloner plusieurs jeux de données à partir de cette source.
```suggestion
de générer toutes les données possibles d'une distribution fixée. On peut alors échantillonner plusieurs jeux de données à partir de cette source.
```

2022-03-22 10:27 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +On peut comparer cet exemple à celui du KNN. Le KNN ne fait que l'hypothèse de continuité, il prédit la valeur d'un point $x$ par rapport
A priori le KNN est présenté plus tard dans le cours, peut être rappeler en une phrase plus clair ce que c'est. Du style : La méthode des k plus proches voisins (ou KNN) consiste, pour estimer la sortie associée à une nouvelle entrée x, à prendre en compte les k échantillons d'apprentissage dont l’entrée est la plus proche de la nouvelle entrée x, selon une distance à définir.

2022-03-22 10:27 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +très élevées pour modéliser précisemment une fonction en tout point.
```suggestion
très élevé pour modéliser précisément une fonction en tout point.
```

2022-03-22 10:27 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +croit exponentiellement avec le nombre de dimensions à nos features.*
à nos features => de nos features ?

2022-03-22 14:09 UTC, tanguyesteoule reviewed
Ok pour ML/5. Je me suis pas trop attardé sur les équations, peut être à revérifier.

Petite remarque général, est-ce qu'en conclusion on ferait pas mieux de mettre des bullets points ? Genre à chaque une liste des points à retenir (de manière très résumé). Ca serait peut être plus lisible.

Sinon bon boulot :+1:

2022-03-22 14:09 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +En résumé, il est nécessaire de choisir les bons biais qui permettront à un modèle de machine learning de bien généraliser.
_machine learning_ sans majuscule alors qu'il y en avait juste au dessus => Il faut harmoniser

2022-03-22 14:09 UTC, tanguyesteoule commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +En résumé, il est nécessaire de choisir les bons biais qui permettront à un modèle de machine learning de bien généraliser.
_machine learning_ sans majuscule alors qu'il y en avait juste au dessus => Il faut harmoniser

2022-03-25 10:14 UTC, Futurne commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +En résumé, il est nécessaire de choisir les bons biais qui permettront à un modèle de machine learning de bien généraliser.
J'ai corrigé et mis des majuscules. Cependant je pense que l'on parlera d'une harmonisation globale sur ces sujets (doit-on parler de loss ou de fonction de perte ? écrivons-nous Machine Learning ou machine learning ? etc...). Donc ces changements ne sont peut-être pas définitifs !

2022-03-25 10:15 UTC, Futurne commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +Le biais et la variance sont deux faces d'une même pièce, ajouter du biais réduit la variance, et vice versa.
En effet c'est probablement plus clair comme cela :P

2022-04-14 02:26 UTC, Futurne commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance.md
> +On peut comparer cet exemple à celui du KNN. Le KNN ne fait que l'hypothèse de continuité, il prédit la valeur d'un point $x$ par rapport
Après concertation avec TheBatz, on a décidé de mettre un chapitre sur le KNN juste après la régression linéaire pour introduire un modèle basique de classification :D

2022-04-17 18:14 UTC, MohamedBsh commented
C’est du beau boulot ! Très fan de la visualisation de la régularisation L1 et L2, on comprend bien l’intuition. Je trouve le cours bien structuré avec des exemples pour illustrer les notions importantes.

Quelques remarques : 

Je reste un peu sur ma faim lorsque tu abordes Elastic Net, je voulais avoir plus de contenu haha. En tant que lecteur j’aimerai savoir quand est-ce je dois, par exemple, utiliser une régression linéaire sans régularisation, avec L1, L2 ou Elastic Net ? Avoir un comparatif.

 Pour répondre à cette question, j'imagine qu’il faut éviter en général de faire des régressions linéaires sans régularisation. Je pense qu’il faudrait donner des intuitions à travers un exemple,qui reprend les différentes méthodes de régularisation, en mettant en avant les avantages/inconvénients.

Quid de Early Stopping ?

Trade off bias/variance : insister dès le départ sur le fait que c’est un résultat théorique important en ML/Stat car il permet de comprendre que l’erreur de généralisation d’un modèle s’exprime à travers la sum de ces deux erreurs : le biais et la variance.

Concernant le biais inductif : 

En amont de ton exemple sur le biais de continuité, j’aurai insisté sur le fait que ça fait partie de “ l'erreur de généralisation” d’un modèle. Que cela est dû à des hypothèses de bases erronées. De manière générale, un modèle à biais élevé est plus susceptible d’underfit les données de train.

Je suis fan de tes explications avec les fonctions/espaces de fonctions mais je ne sais pas si ça sera le cas de tout le monde (notamment des néophytes) qui pourraient apprécier la chose différemment.

2022-04-22 03:57 UTC, Futurne commented
Hello les potes !
J'ai mis à jour le chapitre. Beaucoup de modifs entre cette version et l'ancienne.

J'ai fais ce que j'avais noté sur le channel discord :
* Division en 3 chapitres : une intro générale qui pars d'un exemple pour montrer en cas pratique ce qu'il se passe lorsqu'on évalue les perfs d'un modèle avec et sans régularisation, un chapitre sur la régularisation avec en particulier la présentation de la régularisation L1 et L2, et un chapitre sur le tradeoff biais-variance
* Pour la régularisation, approfondir l'étude des impacts de la régularisation sur la perf et les coefs d'une régression linéaire
* Garder des images avec des plots en français
* Mieux expliquer ce que j'entends pas un espace de recherche de fonction (l'ensemble des fonctions linéaires ax + b peut se définir par des paramètres (a, b) etc...)
* Insister sur l'aspect fondamental du résultat du tradeoff biais-variance
* Un message sur l'erreur de généralisation : Tous les modèles sont faux, mais certains sont utiles 😋  Même les biais les plus simples comme le biais de continuité s'avèrent souvent un peu faux, et il faut faire avec. De plus, il y a toujours du bruit dans les données, source d'erreur irréductible (c.f. équation du tradeoff biais-variance)

Vu que je suis passé sur des notebooks, les équations sont maintenant toutes lisibles directement depuis github :)

Dites moi ce que vous en pensez !

2022-04-23 14:38 UTC, MohamedBsh requested changes

2022-04-23 14:38 UTC, MohamedBsh commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance - une introduction.md
> +les performances du modèle en ajoutant élevant le degré de notre polynôme, mais qu'il fallait être précautionneux
les performances du modèle en augmentant le degré de notre polynôme

2022-04-23 14:38 UTC, MohamedBsh commented on docs/Cours fondamentaux ML/5 - Régularisation & tradeoff biais-variance - une introduction.md
> +par tout modèle de ML.
introduire l'équation ici ? essayer de donner une intuition.

2022-04-23 14:38 UTC, MohamedBsh commented on docs/Cours fondamentaux ML/6 - Régularisation d'un modèle.ipynb
> +      "R² sur le jeu d'entraînement: 1.000\n",
on introduit les métriques classiques dans les autres cours (precision, recall, f1score, ROC, R^2 etc ..) ?

2022-04-23 14:38 UTC, MohamedBsh commented on docs/Cours fondamentaux ML/7 - Tradeoff biais-variance.ipynb
> +    "Il faudrait pouvoir toutes les données possibles (pouvez-vous me trouver toutes les photos de chats et de chiens possibles ?),\n",
Il faudrait avoir toutes les données possibles

2022-04-23 14:38 UTC, MohamedBsh commented on docs/Cours fondamentaux ML/7 - Tradeoff biais-variance.ipynb
> +    "ou faire pile poil les bonnes hypothèses sur la relation afin d'injecter les bons biais au modèle.\n",
ou faire les bonnes hypothèses ... 
On va éviter le pile poil :p

2022-04-23 14:38 UTC, MohamedBsh commented on docs/Cours fondamentaux ML/7 - Tradeoff biais-variance.ipynb
> +    "\\text{loss}_{\\text{test}}(h) & = \\text{variance}(h) + \\text{biais}(h)^2 + \\text{bruit}\\\\\n",
Comme dit précédemment, tu pourrais introduire l'équation dès l'introduction en expliquant brièvement l'intuition (réussir à minimiser l'erreur de généralisation du modèle revient à minimiser la somme de 3 erreurs ...). Tu peux te référer au bouquin de Géron à ce sujet [Hands-On Machine Learning with Scikit-Learn and TensorFlow Concepts, Tools, and Techniques to Build Intelligent Systems] dès p.126 .

<img width="774" alt="Capture d’écran 2022-04-23 à 16 36 34" src="https://user-images.githubusercontent.com/40428556/164910606-020c9fb5-c7f7-421e-8e97-e82d34f7c84b.png">

2022-04-23 21:03 UTC, merged